import { HiOutlineBanknotes } from "react-icons/hi2";
import { FcAssistant, FcAutomotive, FcBiohazard, FcBusinessman, FcButtingIn, FcFactory, FcIcons8Cup, FcIdea, FcInTransit, FcLibrary, FcMultipleDevices, FcOrgUnit } from "react-icons/fc";
import { FaRegCircleCheck } from "react-icons/fa6";
import { FaUsersViewfinder } from "react-icons/fa6";
import { GrOrganization } from "react-icons/gr";
import { VscOrganization } from "react-icons/vsc";
import { GiEgyptianProfile, GiFireZone, GiRamProfile } from "react-icons/gi";
import { RiLockPasswordLine } from "react-icons/ri";
import { MdOutlineBusiness } from "react-icons/md";
import { BsHouseDoor } from "react-icons/bs";
import { LuHotel } from "react-icons/lu";

 const menusContent = [
  {
    _id: 1,
    label: "User Management",
    icon: "products.png",
    page_call: "/User",
    submenu: [
      {
        _id: "65d5cebaee2bb32443dead9c",
        user_id: 33,
        role_id: 1,
        menu_id: 4,
        U_profile_name: "Super Administrator",
        New: false,
        modify: false,
        view: false,
        Delete: false,
        wf_approval: false,
        menutype: "2",
        umenu_Name: "User Role",
        icon: FcBusinessman,
        icon_color:"red",
        c_name: "Satish",
        ul_name: "Satish",
        isDeleted: false,
        createdAt: "2024-02-21T10:21:46.913Z",
        updatedAt: "2024-02-21T10:21:46.913Z",
        page_call: "table/table_user_profile",
        icon_link: "products.png"
      },
      {
        _id: "65d5cebaee2bb32443dead9d",
        user_id: 33,
        role_id: 1,
        menu_id: 5,
        U_profile_name: "Super Administrator",
        New: false,
        modify: false,
        view: false,
        Delete: false,
        wf_approval: false,
        menutype: "2",
        umenu_Name: "Assign Rights -Role Profile",
        icon: FaRegCircleCheck,
        icon_color:"red",
        c_name: "Satish",
        ul_name: "Satish",
        isDeleted: false,
        createdAt: "2024-02-21T10:21:46.913Z",
        updatedAt: "2024-02-21T10:21:46.913Z",
        page_call: "table/table_assign_role",
        icon_link: "products.png"
      },
      {
        _id: "65d5cebaee2bb32443dead9e",
        user_id: 33,
        role_id: 1,
        menu_id: 6,
        U_profile_name: "Super Administrator",
        New: false,
        modify: false,
        view: false,
        Delete: false,
        wf_approval: false,
        menutype: "2",
        umenu_Name: "Manage - User Registeration",
        icon: FaUsersViewfinder,
        icon_color:"green",
        c_name: "Satish",
        ul_name: "Satish",
        isDeleted: false,
        createdAt: "2024-02-21T10:21:46.913Z",
        updatedAt: "2024-02-21T10:21:46.913Z",
        page_call: "table/table_user_information",
        icon_link: "products.png"
      },
      {
        _id: "65d5cebaee2bb32443dead9f",
        user_id: 33,
        role_id: 1,
        menu_id: 8,
        U_profile_name: "Super Administrator",
        New: false,
        modify: false,
        view: false,
        Delete: false,
        wf_approval: false,
        menutype: "2",
        umenu_Name: "Assign User-Company Structure ",
        icon: VscOrganization,
        icon_color:"red",
        c_name: "Satish",
        ul_name: "Satish",
        isDeleted: false,
        createdAt: "2024-02-21T10:21:46.913Z",
        updatedAt: "2024-02-21T10:21:46.913Z",
        page_call: "table/table_user_assign_business",
        icon_link: "products.png"
      },
      {
        _id: "65d5cebaee2bb32443deada0",
        user_id: 33,
        role_id: 1,
        menu_id: 9,
        U_profile_name: "Super Administrator",
        New: false,
        modify: false,
        view: false,
        Delete: false,
        wf_approval: false,
        menutype: "2",
        umenu_Name: "User Profile ",
        icon: GiEgyptianProfile,
        icon_color:"blue",
        c_name: "Satish",
        ul_name: "Satish",
        isDeleted: false,
        createdAt: "2024-02-21T10:21:46.913Z",
        updatedAt: "2024-02-21T10:21:46.913Z",
        page_call: "/User",
        icon_link: "products.png"
      },
      {
        _id: "65d5cebaee2bb32443deada1",
        user_id: 33,
        role_id: 1,
        menu_id: 10,
        U_profile_name: "Super Administrator",
        New: false,
        modify: false,
        view: false,
        Delete: false,
        wf_approval: false,
        menutype: "2",
        umenu_Name: "Forget Password ",
        icon: RiLockPasswordLine,
        icon_color:"teal",
        c_name: "Satish",
        ul_name: "Satish",
        isDeleted: false,
        createdAt: "2024-02-21T10:21:46.913Z",
        updatedAt: "2024-02-21T10:21:46.913Z",
        page_call: "/User",
        icon_link: "products.png"
      }
    ]
  },
  {
    _id: 2,
    label: "Business Stucture ",
    icon: "products.png",
    page_call: "/Bus",
    submenu: [
      {
        _id: "65d5cebaee2bb32443deada3",
        user_id: 33,
        role_id: 1,
        menu_id: 12,
        U_profile_name: "Super Administrator",
        New: false,
        modify: false,
        view: false,
        Delete: false,
        wf_approval: false,
        menutype: "2",
        umenu_Name: "Define Company",
        icon: FcFactory,
        icon_color:"teal",
        c_name: "Satish",
        ul_name: "Satish",
        isDeleted: false,
        createdAt: "2024-02-21T10:21:46.913Z",
        updatedAt: "2024-02-21T10:21:46.913Z",
        page_call: "table/table_company_info",
        icon_link: "products.png"
      },
      {
        _id: "65d5cebaee2bb32443deada4",
        user_id: 33,
        role_id: 1,
        menu_id: 13,
        U_profile_name: "Super Administrator",
        New: false,
        modify: false,
        view: false,
        Delete: false,
        wf_approval: false,
        menutype: "2",
        umenu_Name: "Business Segments",
        icon: MdOutlineBusiness,
        icon_color:"blue",
        c_name: "Satish",
        ul_name: "Satish",
        isDeleted: false,
        createdAt: "2024-02-21T10:21:46.913Z",
        updatedAt: "2024-02-21T10:21:46.913Z",
        page_call: "table/table_business_segment",
        icon_link: "products.png"
      },
      {
        _id: "65d5cebaee2bb32443deada5",
        user_id: 33,
        role_id: 1,
        menu_id: 14,
        U_profile_name: "Super Administrator",
        New: false,
        modify: false,
        view: false,
        Delete: false,
        wf_approval: false,
        menutype: "2",
        umenu_Name: "Business Unit",
        icon: FcOrgUnit,
        icon_color:"teal",
        c_name: "Satish",
        ul_name: "Satish",
        isDeleted: false,
        createdAt: "2024-02-21T10:21:46.913Z",
        updatedAt: "2024-02-21T10:21:46.913Z",
        page_call: "table/table_business_unit_division",
        icon_link: "products.png"
      },
      {
        _id: "65d5cebaee2bb32443deada6",
        user_id: 33,
        role_id: 1,
        menu_id: 15,
        U_profile_name: "Super Administrator",
        New: false,
        modify: false,
        view: false,
        Delete: false,
        wf_approval: false,
        menutype: "2",
        umenu_Name: "Business Zone",
        icon: GiFireZone,
        icon_color:"teal",
        c_name: "Satish",
        ul_name: "Satish",
        isDeleted: false,
        createdAt: "2024-02-21T10:21:46.913Z",
        updatedAt: "2024-02-21T10:21:46.913Z",
        page_call: "table/table_zone",
        icon_link: "products.png"
      },
      {
        _id: "65d5cebaee2bb32443deada7",
        user_id: 33,
        role_id: 1,
        menu_id: 16,
        U_profile_name: "Super Administrator",
        New: false,
        modify: false,
        view: false,
        Delete: false,
        wf_approval: false,
        menutype: "2",
        umenu_Name: "Business Region",
        icon: BsHouseDoor,
        icon_color:"pink",
        c_name: "Satish",
        ul_name: "Satish",
        isDeleted: false,
        createdAt: "2024-02-21T10:21:46.913Z",
        updatedAt: "2024-02-21T10:21:46.913Z",
        page_call: "table/table_region",
        icon_link: "products.png"
      },
      {
        _id: "65d5cebaee2bb32443deada8",
        user_id: 33,
        role_id: 1,
        menu_id: 17,
        U_profile_name: "Super Administrator",
        New: false,
        modify: false,
        view: false,
        Delete: false,
        wf_approval: false,
        menutype: "2",
        umenu_Name: "Business Territory",
        icon: LuHotel,
        icon_color:"pink",
        c_name: "Satish",
        ul_name: "Satish",
        isDeleted: false,
        createdAt: "2024-02-21T10:21:46.913Z",
        updatedAt: "2024-02-21T10:21:46.913Z",
        page_call: "table/table_territory",
        icon_link: "products.png"
      },
      {
        _id: "65d5cebaee2bb32443deada9",
        user_id: 33,
        role_id: 1,
        menu_id: 18,
        U_profile_name: "Super Administrator",
        New: false,
        modify: false,
        view: false,
        Delete: false,
        wf_approval: false,
        menutype: "2",
        umenu_Name: "Business District",
        icon: FcAutomotive,
        icon_color:"pink",
        c_name: "Satish",
        ul_name: "Satish",
        isDeleted: false,
        createdAt: "2024-02-21T10:21:46.914Z",
        updatedAt: "2024-02-21T10:21:46.914Z",
        page_call: "table/table_district",
        icon_link: "products.png"
      },
      {
        _id: "65d5cebaee2bb32443deadaa",
        user_id: 33,
        role_id: 1,
        menu_id: 19,
        U_profile_name: "Super Administrator",
        New: false,
        modify: false,
        view: false,
        Delete: false,
        wf_approval: false,
        menutype: "2",
        umenu_Name: "District / Route",
        icon: FcBiohazard,
        icon_color:"pink",
        c_name: "Satish",
        ul_name: "Satish",
        isDeleted: false,
        createdAt: "2024-02-21T10:21:46.914Z",
        updatedAt: "2024-02-21T10:21:46.914Z",
        page_call: "/Bus",
        icon_link: "products.png"
      },
      {
        _id: "65d5cebaee2bb32443deadab",
        user_id: 33,
        role_id: 1,
        menu_id: 20,
        U_profile_name: "Super Administrator",
        New: false,
        modify: false,
        view: false,
        Delete: false,
        wf_approval: false,
        menutype: "2",
        umenu_Name: "Warehouse Depot",
        icon: FcAssistant,
        icon_color:"pink",
        c_name: "Satish",
        ul_name: "Satish",
        isDeleted: false,
        createdAt: "2024-02-21T10:21:46.914Z",
        updatedAt: "2024-02-21T10:21:46.914Z",
        page_call: "table/table_depot_warehouse",
        icon_link: "products.png"
      },
      {
        _id: "65d5cebaee2bb32443deadac",
        user_id: 33,
        role_id: 1,
        menu_id: 21,
        U_profile_name: "Super Administrator",
        New: false,
        modify: false,
        view: false,
        Delete: false,
        wf_approval: false,
        menutype: "2",
        umenu_Name: "Mapping Depot",
        icon: FcButtingIn,
        icon_color:"pink",
        c_name: "Satish",
        ul_name: "Satish",
        isDeleted: false,
        createdAt: "2024-02-21T10:21:46.914Z",
        updatedAt: "2024-02-21T10:21:46.914Z",
        page_call: "table/table_map_depot",
        icon_link: "products.png"
      }
    ]
  },
  {
    _id: 3,
    label: "Product Management",
    icon: "products.png",
    page_call: "/PRD",
    submenu: [
      {
        _id: "65d5cebaee2bb32443deadae",
        user_id: 33,
        role_id: 1,
        menu_id: 23,
        U_profile_name: "Super Administrator",
        New: false,
        modify: false,
        view: false,
        Delete: false,
        wf_approval: false,
        menutype: "2",
        umenu_Name: "Product Category",
        icon: FcIcons8Cup,
        icon_color:"pink",
        c_name: "Satish",
        ul_name: "Satish",
        isDeleted: false,
        createdAt: "2024-02-21T10:21:46.914Z",
        updatedAt: "2024-02-21T10:21:46.914Z",
        page_call: "table/table_product_category",
        icon_link: "products.png"
      },
      {
        _id: "65d5cebaee2bb32443deadaf",
        user_id: 33,
        role_id: 1,
        menu_id: 24,
        U_profile_name: "Super Administrator",
        New: false,
        modify: false,
        view: false,
        Delete: false,
        wf_approval: false,
        menutype: "2",
        umenu_Name: "Product Segment",
        icon: FcInTransit,
        icon_color:"pink",
        c_name: "Satish",
        ul_name: "Satish",
        isDeleted: false,
        createdAt: "2024-02-21T10:21:46.914Z",
        updatedAt: "2024-02-21T10:21:46.914Z",
        page_call: "table/table_product_segment",
        icon_link: "products.png"
      },
      {
        _id: "65d5cebaee2bb32443deadb0",
        user_id: 33,
        role_id: 1,
        menu_id: 25,
        U_profile_name: "Super Administrator",
        New: false,
        modify: false,
        view: false,
        Delete: false,
        wf_approval: false,
        menutype: "2",
        umenu_Name: "Product Brand",
        icon: FcIdea,
        icon_color:"pink",
        c_name: "Satish",
        ul_name: "Satish",
        isDeleted: false,
        createdAt: "2024-02-21T10:21:46.914Z",
        updatedAt: "2024-02-21T10:21:46.914Z",
        page_call: "table/table_product_brand",
        icon_link: "products.png"
      },
      {
        _id: "65d5cebaee2bb32443deadb1",
        user_id: 33,
        role_id: 1,
        menu_id: 26,
        U_profile_name: "Super Administrator",
        New: false,
        modify: false,
        view: false,
        Delete: false,
        wf_approval: false,
        menutype: "2",
        umenu_Name: "Material SKU",
        icon: FcLibrary,
        icon_color:"pink",
        c_name: "Satish",
        ul_name: "Satish",
        isDeleted: false,
        createdAt: "2024-02-21T10:21:46.914Z",
        updatedAt: "2024-02-21T10:21:46.914Z",
        page_call: "table/table_material_sku",
        icon_link: "products.png"
      },
      {
        _id: "65d5cebaee2bb32443deadb2",
        user_id: 33,
        role_id: 1,
        menu_id: 27,
        U_profile_name: "Super Administrator",
        New: false,
        modify: false,
        view: false,
        Delete: false,
        wf_approval: false,
        menutype: "2",
        umenu_Name: "Material Repository Doc",
        icon: FcMultipleDevices,
        icon_color:"pink",
        c_name: "Satish",
        ul_name: "Satish",
        isDeleted: false,
        createdAt: "2024-02-21T10:21:46.914Z",
        updatedAt: "2024-02-21T10:21:46.914Z",
        page_call: "/PRD",
        icon_link: "products.png"
      }
    ]
  },
  {
    _id: 4,
    label: "Field Assist Management",
    icon: "products.png",
    page_call: "/SCD",
    submenu: [
      {
        _id: "65d5cebaee2bb32443deadb4",
        user_id: 33,
        role_id: 1,
        menu_id: 29,
        U_profile_name: "Super Administrator",
        New: false,
        modify: false,
        view: false,
        Delete: false,
        wf_approval: false,
        menutype: "2",
        umenu_Name: "Define Seasson",
        icon: BsHouseDoor,
        icon_color:"pink",
        c_name: "Satish",
        ul_name: "Satish",
        isDeleted: false,
        createdAt: "2024-02-21T10:21:46.914Z",
        updatedAt: "2024-02-21T10:21:46.914Z",
        page_call: "/SCD",
        icon_link: "products.png"
      },
      {
        _id: "65d5cebaee2bb32443deadb5",
        user_id: 33,
        role_id: 1,
        menu_id: 30,
        U_profile_name: "Super Administrator",
        New: false,
        modify: false,
        view: false,
        Delete: false,
        wf_approval: false,
        menutype: "2",
        umenu_Name: "Crop",
        c_name: "Satish",
        ul_name: "Satish",
        isDeleted: false,
        createdAt: "2024-02-21T10:21:46.914Z",
        updatedAt: "2024-02-21T10:21:46.914Z",
        page_call: "table/table_crop",
        icon_link: "products.png"
      },
      {
        _id: "65d5cebaee2bb32443deadb6",
        user_id: 33,
        role_id: 1,
        menu_id: 31,
        U_profile_name: "Super Administrator",
        New: false,
        modify: false,
        view: false,
        Delete: false,
        wf_approval: false,
        menutype: "2",
        umenu_Name: "Village Info",
        c_name: "Satish",
        ul_name: "Satish",
        isDeleted: false,
        createdAt: "2024-02-21T10:21:46.914Z",
        updatedAt: "2024-02-21T10:21:46.914Z",
        page_call: "table/table_village",
        icon_link: "products.png"
      },
      {
        _id: "65d5cebaee2bb32443deadb7",
        user_id: 33,
        role_id: 1,
        menu_id: 32,
        U_profile_name: "Super Administrator",
        New: false,
        modify: false,
        view: false,
        Delete: false,
        wf_approval: false,
        menutype: "2",
        umenu_Name: "Farmer Info",
        c_name: "Satish",
        ul_name: "Satish",
        isDeleted: false,
        createdAt: "2024-02-21T10:21:46.914Z",
        updatedAt: "2024-02-21T10:21:46.914Z",
        page_call: "table/table_farmer",
        icon_link: "products.png"
      },
      {
        _id: "65d5cebaee2bb32443deadb8",
        user_id: 33,
        role_id: 1,
        menu_id: 33,
        U_profile_name: "Super Administrator",
        New: false,
        modify: false,
        view: false,
        Delete: false,
        wf_approval: false,
        menutype: "2",
        umenu_Name: "Manage Area / Route",
        c_name: "Satish",
        ul_name: "Satish",
        isDeleted: false,
        createdAt: "2024-02-21T10:21:46.915Z",
        updatedAt: "2024-02-21T10:21:46.915Z",
        page_call: "/SCD",
        icon_link: "products.png"
      }
    ]
  },
  {
    _id: 5,
    label: "Employee Management",
    icon: "products.png",
    page_call: "/EMP",
    submenu: [
      {
        _id: "65d5cebaee2bb32443deadba",
        user_id: 33,
        role_id: 1,
        menu_id: 35,
        U_profile_name: "Super Administrator",
        New: false,
        modify: false,
        view: false,
        Delete: false,
        wf_approval: false,
        menutype: "2",
        umenu_Name: "Manage Employee",
        c_name: "Satish",
        ul_name: "Satish",
        isDeleted: false,
        createdAt: "2024-02-21T10:21:46.915Z",
        updatedAt: "2024-02-21T10:21:46.915Z",
        page_call: "table/table_employee",
        icon_link: "products.png"
      },
      {
        _id: "65d5cebaee2bb32443deadbb",
        user_id: 33,
        role_id: 1,
        menu_id: 36,
        U_profile_name: "Super Administrator",
        New: false,
        modify: false,
        view: false,
        Delete: false,
        wf_approval: false,
        menutype: "2",
        umenu_Name: "Employee Assign to User",
        c_name: "Satish",
        ul_name: "Satish",
        isDeleted: false,
        createdAt: "2024-02-21T10:21:46.915Z",
        updatedAt: "2024-02-21T10:21:46.915Z",
        page_call: "/EMP",
        icon_link: "products.png"
      }
    ]
  },
  {
    _id: 6,
    label: "Transaction",
    icon: "products.png",
    page_call: "/RP",
    submenu: [
      {
        _id: "65d5cebaee2bb32443deadbd",
        user_id: 33,
        role_id: 1,
        menu_id: 38,
        U_profile_name: "Super Administrator",
        New: false,
        modify: false,
        view: false,
        Delete: false,
        wf_approval: false,
        menutype: "2",
        umenu_Name: "Annual Sales Plan",
        c_name: "Satish",
        ul_name: "Satish",
        isDeleted: false,
        createdAt: "2024-02-21T10:21:46.915Z",
        updatedAt: "2024-02-21T10:21:46.915Z",
        page_call: "dealerform_details",
        icon_link: "products.png"
      },
      {
        _id: "65d5cebaee2bb32443deadbe",
        user_id: 33,
        role_id: 1,
        menu_id: 39,
        U_profile_name: "Super Administrator",
        New: false,
        modify: false,
        view: false,
        Delete: false,
        wf_approval: false,
        menutype: "2",
        umenu_Name: "Rolling Plan",
        c_name: "Satish",
        ul_name: "Satish",
        isDeleted: false,
        createdAt: "2024-02-21T10:21:46.915Z",
        updatedAt: "2024-02-21T10:21:46.915Z",
        page_call: "rollingplans",
        icon_link: "products.png"
      },
      {
        _id: "65d5cebaee2bb32443deadbf",
        user_id: 33,
        role_id: 1,
        menu_id: 40,
        U_profile_name: "Super Administrator",
        New: false,
        modify: false,
        view: false,
        Delete: false,
        wf_approval: false,
        menutype: "2",
        umenu_Name: "Collection Plan",
        c_name: "Satish",
        ul_name: "Satish",
        isDeleted: false,
        createdAt: "2024-02-21T10:21:46.915Z",
        updatedAt: "2024-02-21T10:21:46.915Z",
        page_call: "collectionplans",
        icon_link: "products.png"
      },
      {
        _id: "65d5cebaee2bb32443deadc1",
        user_id: 33,
        role_id: 1,
        menu_id: 42,
        U_profile_name: "Super Administrator",
        New: false,
        modify: false,
        view: false,
        Delete: false,
        wf_approval: false,
        menutype: "2",
        umenu_Name: "Manage Dealer",
        c_name: "Satish",
        ul_name: "Satish",
        isDeleted: false,
        createdAt: "2024-02-21T10:21:46.915Z",
        updatedAt: "2024-02-21T10:21:46.915Z",
        page_call: "table/table_dealer",
        icon_link: "products.png"
      }
    ]
  },
  {
    _id: 2,
    label: "Open Period Transaction",
    icon: "products.png",
    page_call: "table/table_transaction_open",
    submenu: []
  }
];

export default menusContent
