import React, { useState } from "react";
import Image from "next/image";
import { BsCheck2Circle } from "react-icons/bs";
import { AiOutlineDelete } from "react-icons/ai";

const AdditionalInfo = (props) => {
  const [formActive, setFormActive] = useState(false);
  const [userImage, setUserImage] = useState("");

  const currentYear = new Date().getFullYear();
  const nextYears = Array.from(
    { length: 10 },
    (_, index) => currentYear + index
  );

  //dummyData

  const data = [
    {
      id: 1,
      name: "Example A",
      profit: "New",
      relation: 10,
      son_of: "$1,000,000",
      pan: "Product Brand",
      aadhar: "X",
    },
    {
      id: 2,
      name: "Example B",
      profit: "Commercial",
      relation: 5,
      son_of: "$500,000",
      pan: "Product Brand",
      aadhar: "X",
    },
    {
      id: 2,
      name: "Example B",
      profit: "Commercial",
      relation: 5,
      son_of: "$500,000",
      pan: "Product Brand",
      aadhar: "X",
    },
  ];

  return (
    <div className="bg-white rounded p-4 w-full overflow-auto">
      {/* Filters */}
      <div className="mb-8">
        <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
          <div>
            <label className="text-black">Company</label>
            <select
              className="block w-full text-black border border-gray-400 rounded py-2 px-4"
              defaultValue=""
            >
              <option value="">Select Company</option>
              {/* Add company options */}
            </select>
          </div>
          <div>
            <label className="text-black">Crop Name</label>
            <select
              className="block w-full text-black border border-gray-400 rounded py-2 px-4"
              defaultValue=""
            >
              <option value="">Select Crop</option>
              {/* Add crop options */}
            </select>
          </div>
          <div>
            <label className="text-black">Season</label>
            <input
              className="block w-full text-black border border-gray-400 rounded py-2 px-4"
              type="text"
              value="Autogenerated Season"
              disabled
            />
          </div>
        </div>
      </div>

      {/* Form */}
      <form>
        <div className="mb-8">
          <h2 className="text-xl font-bold mb-4">
            Crop Details (District Level)
          </h2>
          <div className="overflow-x-auto">
            <table className="border-collapse border border-gray-400 w-full">
              <colgroup>
                <col style={{ width: "15%" }} /> 
                <col style={{ width: "14%" }} /> 
                <col style={{ width: "11%" }} /> 
                <col style={{ width: "10%" }} /> 
                <col style={{ width: "10%" }} /> 
                <col style={{ width: "10%" }} /> 
                <col style={{ width: "10%" }} /> 
                <col style={{ width: "10%" }} /> 
                <col style={{ width: "20%" }} /> 
              </colgroup>
              <thead>
                <tr className="bg-orange-500 text-white">
                  <th className="border border-gray-400 px-4 py-2">District</th>
                  <th className="border border-gray-400 px-4 py-2">
                    Total Cultivated Area (In acre)
                  </th>
                  <th className="border border-gray-400 px-4 py-2">
                    Area (In acre)
                  </th>
                  <th className="border border-gray-400 px-4 py-2">Share %</th>
                  <th className="border border-gray-400 px-4 py-2">
                    Average Yield/acre (Qtl.)
                  </th>
                  <th className="border border-gray-400 px-4 py-2">
                    Current Price/Qtl.
                  </th>
                  <th className="border border-gray-400 px-4 py-2">
                    Input Cost (INR)
                  </th>
                  <th className="border border-gray-400 px-4 py-2">
                    Output Cost (INR)
                  </th>
                  <th className="border border-gray-400 px-4 py-2">ROI</th>
                </tr>
              </thead>
              <tbody>
                <tr>
                  <td className="border border-gray-400 px-4 py-2">
                    <select className="w-full px-2 py-1 border border-gray-300 rounded">
                      <option value="0">0</option>
                      <option value="10">10mfvonasf</option>
                     
                    </select>
                  </td>
                  <td className="border border-gray-400 px-4 py-2">
                    <input
                      type="number"
                      className="w-full px-2 py-1 border border-gray-300 rounded"
                    />
                  </td>
                  <td className="border border-gray-400 px-4 py-2">
                    <input
                      type="number"
                      className="w-full px-2 py-1 border border-gray-300 rounded"
                    />
                  </td>
                  <td className="border border-gray-400 px-4 py-2">
                    <input
                      type="number"
                      className="w-full px-2 py-1 border border-gray-300 rounded"
                      disabled
                    />
                  </td>
                  <td className="border border-gray-400 px-4 py-2">
                    <input
                      type="number"
                      className="w-full px-2 py-1 border border-gray-300 rounded"
                    />
                  </td>
                  <td className="border border-gray-400 px-4 py-2">
                    <input
                      type="number"
                      className="w-full px-2 py-1 border border-gray-300 rounded"
                    />
                  </td>
                  <td className="border border-gray-400 px-4 py-2">
                    <input
                      type="number"
                      className="w-full px-2 py-1 border border-gray-300 rounded"
                    />
                  </td>
                  <td className="border border-gray-400 px-4 py-2">
                    <input
                      type="number"
                      className="w-full px-2 py-1 border border-gray-300 rounded"
                    />
                  </td>
                  <td className="border border-gray-400 px-4 py-2">
                    <input
                      type="number"
                      className="w-full px-2 py-1 border border-gray-300 rounded"
                      disabled
                    />
                  </td>
                </tr>
                {/* Add more rows as needed */}
                <tr className="bg-gray-900 text-white">
                  <td className="border border-gray-400 px-4 py-2">Total</td>
                  <td className="border border-gray-400 px-4 py-2">-</td>
                  <td className="border border-gray-400 px-4 py-2">-</td>
                  <td className="border border-gray-400 px-4 py-2">-</td>
                  <td className="border border-gray-400 px-4 py-2">-</td>
                  <td className="border border-gray-400 px-4 py-2">-</td>
                  <td className="border border-gray-400 px-4 py-2">-</td>
                  <td className="border border-gray-400 px-4 py-2">-</td>
                  <td className="border border-gray-400 px-4 py-2">-</td>
                </tr>
              </tbody>
            </table>
          </div>
        </div>

        <div className="mb-8">
          <h2 className="text-xl font-bold mb-4">
            Crop Segmentation (District Level)
          </h2>
          <div className="overflow-x-auto">
            <table className="border-collapse border border-gray-400 w-full">
              <colgroup>
                <col style={{ width: "10%" }} /> {/* Adjust width as needed */}
                <col style={{ width: "9%" }} /> {/* Adjust width as needed */}
                <col style={{ width: "9%" }} /> {/* Adjust width as needed */}
                <col style={{ width: "9%" }} /> {/* Adjust width as needed */}
                <col style={{ width: "9%" }} /> {/* Adjust width as needed */}
                <col style={{ width: "9%" }} /> {/* Adjust width as needed */}
                <col style={{ width: "9%" }} /> {/* Adjust width as needed */}
                <col style={{ width: "9%" }} /> {/* Adjust width as needed */}
                <col style={{ width: "9%" }} /> {/* Adjust width as needed */}
                <col style={{ width: "9%" }} /> {/* Adjust width as needed */}
                <col style={{ width: "9%" }} /> {/* Adjust width as needed */}
              </colgroup>
              <thead>
                <tr className="bg-orange-500 text-white">
                  <th className="border border-gray-400 px-4 py-2">
                    Crop Stage
                  </th>
                  <th className="border border-gray-400 px-4 py-2">Segment</th>
                  <th className="border border-gray-400 px-4 py-2">
                    Product / Brand
                  </th>
                  <th className="border border-gray-400 px-4 py-2">Share %</th>
                  <th className="border border-gray-400 px-4 py-2">
                    Dose/Acre (kg/ltr)
                  </th>
                  <th className="border border-gray-400 px-4 py-2">
                    Cost/Acre (INR)
                  </th>
                  <th className="border border-gray-400 px-4 py-2">
                    Average Cost/Acre (INR)
                  </th>
                  <th className="border border-gray-400 px-4 py-2">
                    Start Date
                  </th>
                  <th className="border border-gray-400 px-4 py-2">End Date</th>
                  <th className="border border-gray-400 px-4 py-2">
                    Total Days
                  </th>
                  <th className="border border-gray-400 px-4 py-2">Stage</th>
                </tr>
              </thead>
              <tbody>
                <tr>
                  <td className="border border-gray-400 px-4 py-2">
                    <input
                      type="text"
                      className="w-full px-2 py-1 border border-gray-300 rounded"
                    />
                  </td>
                  <td className="border border-gray-400 px-4 py-2">
                    <select className="w-full px-2 py-1 border border-gray-300 rounded">
                      <option value="0">0</option>
                      <option value="10">10mfvonasf</option>
                      {/* Add more options as needed */}
                    </select>
                  </td>
                  <td className="border border-gray-400 px-4 py-2">
                    <select className="w-full px-2 py-1 border border-gray-300 rounded">
                      <option value="0">0</option>
                      <option value="10">10mfvonasf</option>
                      {/* Add more options as needed */}
                    </select>
                  </td>
                  <td className="border border-gray-400 px-4 py-2">
                    <input
                      type="number"
                      className="w-full px-2 py-1 border border-gray-300 rounded"
                      disabled
                    />
                  </td>
                  <td className="border border-gray-400 px-4 py-2">
                    <input
                      type="number"
                      className="w-full px-2 py-1 border border-gray-300 rounded"
                    />
                  </td>
                  <td className="border border-gray-400 px-4 py-2">
                    <input
                      type="number"
                      className="w-full px-2 py-1 border border-gray-300 rounded"
                      disabled
                    />
                  </td>
                  <td className="border border-gray-400 px-4 py-2">
                    <input
                      type="number"
                      className="w-full px-2 py-1 border border-gray-300 rounded"
                      disabled
                    />
                  </td>
                  <td className="border border-gray-400 px-4 py-2">
                    <input
                      type="date"
                      className="w-full px-2 py-1 border border-gray-300 rounded"
                    />
                  </td>
                  <td className="border border-gray-400 px-4 py-2">
                    <input
                      type="date"
                      className="w-full px-2 py-1 border border-gray-300 rounded"
                    />
                  </td>
                  <td className="border border-gray-400 px-4 py-2">
                    <input
                      type="number"
                      className="w-full px-2 py-1 border border-gray-300 rounded"
                      disabled
                    />
                  </td>
                  <td className="border border-gray-400 px-4 py-2">
                    <select className="w-full px-2 py-1 border border-gray-300 rounded">
                      <option value="0">0</option>
                      <option value="10">10mfvonasf</option>
                      {/* Add more options as needed */}
                    </select>
                  </td>
                </tr>
                {/* Add more rows as needed */}
                <tr className="bg-gray-900 text-white">
                  <td className="border border-gray-400 px-4 py-2">Total</td>
                  <td className="border border-gray-400 px-4 py-2">-</td>
                  <td className="border border-gray-400 px-4 py-2">-</td>
                  <td className="border border-gray-400 px-4 py-2">-</td>
                  <td className="border border-gray-400 px-4 py-2">-</td>
                  <td className="border border-gray-400 px-4 py-2">-</td>
                  <td className="border border-gray-400 px-4 py-2">-</td>
                  <td className="border border-gray-400 px-4 py-2">-</td>
                  <td className="border border-gray-400 px-4 py-2">-</td>
                  <td className="border border-gray-400 px-4 py-2">-</td>
                  <td className="border border-gray-400 px-4 py-2">-</td>
                </tr>
              </tbody>
            </table>
          </div>
        </div>

        <div className="mb-8">
          <h2 className="text-xl font-bold mb-4">
            Crop Market Share (District Level)
          </h2>
          <div className="overflow-x-auto">
            <table className="border-collapse border border-gray-400 w-full">
              <colgroup>
                <col style={{ width: "10%" }} /> {/* Adjust width as needed */}
                <col style={{ width: "9%" }} /> {/* Adjust width as needed */}
                <col style={{ width: "9%" }} /> {/* Adjust width as needed */}
                <col style={{ width: "9%" }} /> {/* Adjust width as needed */}
              </colgroup>
              <thead>
                <tr className="bg-orange-500 text-white">
                  <th className="border border-gray-400 px-4 py-2">
                    Market/Mandi Name
                  </th>

                  <th className="border border-gray-400 px-4 py-2">
                    Market Potential (Lakh)
                  </th>
                  <th className="border border-gray-400 px-4 py-2">
                    Our Business(Lakh)
                  </th>
                  <th className="border border-gray-400 px-4 py-2">
                    Our Share
                  </th>
                </tr>
              </thead>
              <tbody>
                <tr>
                  <td className="border border-gray-400 px-4 py-2">
                    <select className="w-full px-2 py-1 border border-gray-300 rounded">
                      <option value="0">0</option>
                      <option value="10">10mfvonasf</option>
                      {/* Add more options as needed */}
                    </select>
                  </td>
                  <td className="border border-gray-400 px-4 py-2">
                    <input
                      type="number"
                      className="w-full px-2 py-1 border border-gray-300 rounded"
                    />
                  </td>
                  <td className="border border-gray-400 px-4 py-2">
                    <input
                      type="number"
                      className="w-full px-2 py-1 border border-gray-300 rounded"
                    />
                  </td>
                  <td className="border border-gray-400 px-4 py-2">
                    <input
                      type="number"
                      className="w-full px-2 py-1 border border-gray-300 rounded"
                      disabled
                    />
                  </td>
                </tr>
                {/* Add more rows as needed */}
                <tr className="bg-gray-900 text-white">
                  <td className="border border-gray-400 px-4 py-2">Total</td>
                  <td className="border border-gray-400 px-4 py-2">-</td>
                  <td className="border border-gray-400 px-4 py-2">-</td>
                  <td className="border border-gray-400 px-4 py-2">-</td>
                </tr>
              </tbody>
            </table>
          </div>

          <div className="w-full flex mt-12 gap-12">
            <button
              className="text-center rounded-md bg-green-500 text-white py-1 px-4 text-lg"
              type="submit"
            >
              Submit
            </button>
            <button
              className="text-center rounded-md bg-green-500 text-white py-1 px-4 text-lg"
              type="submit"
            >
              Close
            </button>
          </div>
        </div>
        {/* Additional Sections */}
      </form>
    </div>
  );
};

export default AdditionalInfo;
