const zonelabel =[
"East Zone-01-NES",
"East Zone-02-ROE",
"North Zone-01",
"North Zone-02",
"North Zone-03",
"SZ-1 Costal Andhra",
"SZ-2 Rayalaseema & Telangana",
"SZ-3 Karnataka",
"SZ-4 Tamilnadu",
"West Zone-01",
"West Zone-02",
]

const regionLable =[
    "Akola",
    "Bellary",
    "Bhatinda",
    "Bhopal",
    "Ganganagar",
    "Guj",
    "Guj",
    "Gulbarga",
    "Guntur",
    "Harda",
    "Himachal",
    "Hissar",
    "Hyderabad",
    "Indore",
    "Jabalpur",
    "Jaipur",
    "Jalandhar",
    "Jodhpur",
    "Kanchipuram",
    "Karnal",
    "Kashmir",
    "Kota",
    "Kurnool",
    "Mysore",
    "Nagpur",
    "Nagpur",
    "Nagpur",
    "Nanded",
    "Nandyal",
    "Nashik",
    "Nellore",
    "NES",
    "NES",
    "Nimar",
    "Patiala",
    "Pune",
    "Pune",
    "Rajahmundry",
    "ROE",
    "ROE",
    "ROE",
    "ROE",
    "Sagar",
    "Sangli",
    "Tadepalligudem",
    "Trichy",
    "Ujjain",
    "UP",
    "UPE",
    "UPW",
    "UPW",
    "UPW",
    "Vijayawada",
    "Warangal",
]

const territoryLable=[
    "Abohar",
    "Adilabad",
    "Adoni",
    "Agra",
    "Ahmednagar",
    "Akola",
    "Aligarh",
    "Allagadda",
    "Alwar",
    "Ambala",
    "Ambikapur",
    "Amravati",
    "Amreli",
    "Amritsar",
    "Ananthapur",
    "Anupgarh",
    "Arambagh",
    "Ashoknagar",
    "Atmakur",
    "Badaun",
    "Badnagar",
    "Badwani",
    "Bagarh",
    "Balaghat",
    "Ballia",
    "Baltora",
    "Banswara",
    "Baramati",
    "Baran",
    "Barnala",
    "Barpeta",
    "Basti",
    "Bathinda",
    "Beed",
    "Behraich",
    "Belgaum",
    "Bellary",
    "Berhmpore",
    "Betul",
    "Bhadrachalam",
    "Bhadrak",
    "Bhavnagar",
]

export {zonelabel, regionLable,territoryLable}